import { Router } from "express";
import tasksRouter from "./tasks";
import executionsRouter from "./executions";
import focusRouter from "./focus";
import templatesRouter from "./templates";
import timeSlotsRouter from "./timeSlots";
import schedulesRouter from "./schedules";
import dependenciesRouter from "./dependencies";
import subtasksRouter from "./subtasks";
import linksRouter from "./links";
import knowledgePointsRouter from "./knowledgePoints";
import analyticsRouter from "./analytics";
import recommendationsRouter from "./recommendations";
import progressRouter from "./progress";
import progressSyncRouter from "./progressSync";
import settingsRouter from "./settings";
import unifiedReviewRouter from "./unifiedReview";
import learningLoopsRouter from "./learningLoops";

const router = Router();

router.use(tasksRouter);
router.use(executionsRouter);
router.use(focusRouter);
router.use(templatesRouter);
router.use(timeSlotsRouter);
router.use(schedulesRouter);
router.use(dependenciesRouter);
router.use(subtasksRouter);
router.use(linksRouter);
router.use(knowledgePointsRouter);
router.use(analyticsRouter);
router.use(recommendationsRouter);
router.use(progressRouter);
router.use(progressSyncRouter);
router.use(settingsRouter);
router.use(unifiedReviewRouter);
router.use(learningLoopsRouter);

export default router;
