import type { IAuthApi } from './IAuthApi';
import type { IGraphsApi } from './IGraphsApi';
import type { INodesApi } from './INodesApi';
import type { IEdgesApi } from './IEdgesApi';
import type { IAiApi, IAiActionsApi } from './IAiApi';
import type { IStudyApi } from './IStudyApi';
import type { IDashboardApi } from './IDashboardApi';
import type { IStatisticsApi } from './IStatisticsApi';
import type { IQuizApi } from './IQuizApi';
import type { IAchievementsApi } from './IAchievementsApi';
import type { IPeriodicTasksApi } from './IPeriodicTasksApi';
import type { IKnowledgePointsApi, IGraphNodesApi, ICombinedViewApi } from './IKnowledgePointsApi';
import type { ISchedulerApi } from './ISchedulerApi';
import type { ITtsApi } from './ITtsApi';
import type { ISttApi } from './ISttApi';
import type { ITasksApi, ISearchApi, IDataApi } from './ITasksApi';
import type { ITemplatesApi, IPromptsApi, IFocusApi } from './ITemplatesApi';
import type { ILearningPathsApi, ILearningPathApi } from './ILearningPathsApi';
import type { IRagApi } from './IRagApi';
import type { IAutoGraphApi } from './IAutoGraphApi';
import type { IHealthApi } from './IHealthApi';
import type { IBackupApi } from './IBackupApi';
import type { IPerformanceApi } from './IPerformanceApi';
import type { IAgentApi } from './IAgentApi';
import type { IDomainsApi, IGraphDomainsApi } from './IDomainsApi';
import type { IPluginsApi } from './IPluginsApi';
import type { ILiteratureApi } from './ILiteratureApi';
import type { IRegionsApi } from './IRegionsApi';
import type { IStoryCreationApi } from './IStoryCreationApi';
import type { IConceptAggregationApi } from './IConceptAggregationApi';
import type { IGraphVersionsApi } from './IGraphVersionsApi';

export interface IApi {
  auth: IAuthApi;
  graphs: IGraphsApi;
  nodes: INodesApi;
  edges: IEdgesApi;
  knowledgePoints: IKnowledgePointsApi;
  graphNodes: IGraphNodesApi;
  combinedView: ICombinedViewApi;
  ai: IAiApi;
  aiActions: IAiActionsApi;
  tts: ITtsApi;
  stt: ISttApi;
  study: IStudyApi;
  dashboard: IDashboardApi;
  statistics: IStatisticsApi;
  tasks: ITasksApi;
  search: ISearchApi;
  data: IDataApi;
  templates: ITemplatesApi;
  prompts: IPromptsApi;
  focus: IFocusApi;
  achievements: IAchievementsApi;
  periodicTasks: IPeriodicTasksApi;
  learningPaths: ILearningPathsApi;
  learningPath: ILearningPathApi;
  rag: IRagApi;
  autoGraph: IAutoGraphApi;
  health: IHealthApi;
  backup: IBackupApi;
  quiz: IQuizApi;
  agent: IAgentApi;
  scheduler: ISchedulerApi;
  performance: IPerformanceApi;
  domains: IDomainsApi;
  graphDomains: IGraphDomainsApi;
  plugins: IPluginsApi;
  literature: ILiteratureApi;
  regions: IRegionsApi;
  storyCreation: IStoryCreationApi;
  conceptAggregation: IConceptAggregationApi;
  graphVersions: IGraphVersionsApi;
}