import type {
  BackboneModulePreset,
} from "@shared/types/graph";

export const ACADEMIC_RESEARCH = {
  id: "academic_research" as const,
  name: "通用学术研究",
  description: "适用于通用学术研究领域，包含研究背景、文献综述、研究方法、核心概念、应用领域、未来方向六个标准模块",
  moduleTypes: [
    "research_background",
    "literature_review",
    "research_methods",
    "core_concepts",
    "application_domains",
    "future_directions",
  ],
  modules: [
    {
      module_type: "research_background",
      title: "研究背景",
      icon: "📚",
      color: "#6366F1",
      description: "研究主题的背景信息、发展历程和现状",
      suggestedNodes: ["研究背景", "发展历程", "研究现状", "问题陈述"],
      relationshipToCore: "提供研究的基础和动机",
    },
    {
      module_type: "literature_review",
      title: "文献综述",
      icon: "📄",
      color: "#8B5CF6",
      description: "相关文献的综述和分析",
      suggestedNodes: ["理论基础", "相关工作", "研究空白", "文献分析"],
      relationshipToCore: "建立理论基础和研究脉络",
    },
    {
      module_type: "research_methods",
      title: "研究方法",
      icon: "🔬",
      color: "#3B82F6",
      description: "研究采用的方法论和技术手段",
      suggestedNodes: ["研究方法", "技术路线", "实验设计", "数据分析"],
      relationshipToCore: "提供研究的实施路径",
    },
    {
      module_type: "core_concepts",
      title: "核心概念",
      icon: "💡",
      color: "#10B981",
      description: "研究的核心概念、定义和理论框架",
      suggestedNodes: ["核心概念", "关键定义", "理论框架", "主要发现"],
      relationshipToCore: "研究的核心内容和贡献",
    },
    {
      module_type: "application_domains",
      title: "应用领域",
      icon: "🎯",
      color: "#F59E0B",
      description: "研究成果的应用领域和实际场景",
      suggestedNodes: ["应用场景", "实践案例", "行业应用", "工具实现"],
      relationshipToCore: "展示研究的实际价值",
    },
    {
      module_type: "future_directions",
      title: "未来方向",
      icon: "🚀",
      color: "#EC4899",
      description: "未来研究方向和发展趋势",
      suggestedNodes: ["研究展望", "发展趋势", "开放问题", "潜在方向"],
      relationshipToCore: "指明后续研究方向",
    },
  ],
} satisfies BackboneModulePreset;

export const EXPERIMENTAL_SCIENCE = {
  id: "experimental_science" as const,
  name: "实验科学研究",
  description: "适用于实验科学领域，包含研究背景、文献综述、实验设计、数据收集、结果分析、应用领域六个模块",
  moduleTypes: [
    "research_background",
    "literature_review",
    "experiment_design",
    "data_collection",
    "result_analysis",
    "application_domains",
  ],
  modules: [
    {
      module_type: "research_background",
      title: "研究背景",
      icon: "📚",
      color: "#6366F1",
      description: "研究主题的背景信息、发展历程和研究动机",
      suggestedNodes: ["研究背景", "问题陈述", "研究意义"],
      relationshipToCore: "提供研究的基础和动机",
    },
    {
      module_type: "literature_review",
      title: "文献综述",
      icon: "📄",
      color: "#8B5CF6",
      description: "相关文献的综述和理论基础",
      suggestedNodes: ["理论基础", "相关工作", "研究空白"],
      relationshipToCore: "建立理论基础和研究脉络",
    },
    {
      module_type: "experiment_design",
      title: "实验设计",
      icon: "🧪",
      color: "#3B82F6",
      description: "实验方案设计和实施流程",
      suggestedNodes: ["实验方案", "对照组设计", "变量控制", "实验工具"],
      relationshipToCore: "确保实验的可靠性和有效性",
    },
    {
      module_type: "data_collection",
      title: "数据收集",
      icon: "📊",
      color: "#10B981",
      description: "数据采集方法和数据处理流程",
      suggestedNodes: ["数据来源", "采集方法", "数据处理", "质量控制"],
      relationshipToCore: "保障数据质量和完整性",
    },
    {
      module_type: "result_analysis",
      title: "结果分析",
      icon: "📈",
      color: "#F59E0B",
      description: "实验结果分析和结论推导",
      suggestedNodes: ["统计分析", "结果解读", "假设验证", "误差分析"],
      relationshipToCore: "从数据中提取科学结论",
    },
    {
      module_type: "application_domains",
      title: "应用领域",
      icon: "🎯",
      color: "#EC4899",
      description: "研究成果的应用前景和实际场景",
      suggestedNodes: ["应用场景", "实践意义", "未来方向"],
      relationshipToCore: "展示研究的实际价值",
    },
  ],
} satisfies BackboneModulePreset;

export const ENGINEERING_RESEARCH = {
  id: "engineering_research" as const,
  name: "工程技术研究",
  description: "适用于工程技术研究领域，包含问题背景、技术架构、工程实现、性能评估、应用案例、未来方向六个模块",
  moduleTypes: [
    "problem_background",
    "tech_architecture",
    "engineering_implementation",
    "performance_evaluation",
    "application_cases",
    "future_directions",
  ],
  modules: [
    {
      module_type: "problem_background",
      title: "问题背景",
      icon: "📚",
      color: "#6366F1",
      description: "工程问题的背景和需求分析",
      suggestedNodes: ["问题定义", "需求分析", "现有方案", "技术挑战"],
      relationshipToCore: "明确工程目标和约束条件",
    },
    {
      module_type: "tech_architecture",
      title: "技术架构",
      icon: "🏗️",
      color: "#8B5CF6",
      description: "系统的技术架构设计方案",
      suggestedNodes: ["架构设计", "技术选型", "模块划分", "接口定义"],
      relationshipToCore: "提供系统的整体蓝图",
    },
    {
      module_type: "engineering_implementation",
      title: "工程实现",
      icon: "⚙️",
      color: "#3B82F6",
      description: "具体的工程实现方案和技术细节",
      suggestedNodes: ["核心实现", "关键技术", "实现难点", "优化方案"],
      relationshipToCore: "将设计转化为可运行系统",
    },
    {
      module_type: "performance_evaluation",
      title: "性能评估",
      icon: "📊",
      color: "#10B981",
      description: "系统性能测试和评估结果",
      suggestedNodes: ["性能指标", "测试方法", "评估结果", "对比分析"],
      relationshipToCore: "验证系统是否达到预期目标",
    },
    {
      module_type: "application_cases",
      title: "应用案例",
      icon: "🎯",
      color: "#F59E0B",
      description: "系统在实际场景中的应用案例",
      suggestedNodes: ["应用场景", "案例分析", "用户反馈", "部署方案"],
      relationshipToCore: "展示系统的实际应用价值",
    },
    {
      module_type: "future_directions",
      title: "未来方向",
      icon: "🚀",
      color: "#EC4899",
      description: "未来的优化方向和发展规划",
      suggestedNodes: ["技术演进", "功能扩展", "性能优化", "生态建设"],
      relationshipToCore: "指明系统的后续发展方向",
    },
  ],
} satisfies BackboneModulePreset;

export const POLICY_RESEARCH = {
  id: "policy_research" as const,
  name: "政策研究",
  description: "适用于政策研究领域，包含政策背景、政策工具、实施机制、影响评估、案例分析、政策建议六个模块",
  moduleTypes: [
    "policy_background",
    "policy_instruments",
    "implementation_mechanism",
    "impact_evaluation",
    "case_studies",
    "policy_recommendations",
  ],
  modules: [
    {
      module_type: "policy_background",
      title: "政策背景",
      icon: "📚",
      color: "#6366F1",
      description: "政策出台的背景、历史沿革和政策环境",
      suggestedNodes: ["政策背景", "历史沿革", "政策环境", "问题界定"],
      relationshipToCore: "理解政策制定的大环境",
    },
    {
      module_type: "policy_instruments",
      title: "政策工具",
      icon: "🔧",
      color: "#8B5CF6",
      description: "政策采用的工具和手段",
      suggestedNodes: ["政策工具", "配套措施", "资源配置", "制度设计"],
      relationshipToCore: "明确政策实施的具体手段",
    },
    {
      module_type: "implementation_mechanism",
      title: "实施机制",
      icon: "⚙️",
      color: "#3B82F6",
      description: "政策的执行机制和落地方式",
      suggestedNodes: ["执行机制", "责任分工", "监督机制", "协调机制"],
      relationshipToCore: "确保政策能有效落地",
    },
    {
      module_type: "impact_evaluation",
      title: "影响评估",
      icon: "📊",
      color: "#10B981",
      description: "政策实施效果和影响的评估",
      suggestedNodes: ["效果评估", "社会影响", "经济影响", "环境影响"],
      relationshipToCore: "衡量政策的实际效果",
    },
    {
      module_type: "case_studies",
      title: "案例分析",
      icon: "📋",
      color: "#F59E0B",
      description: "国内外相关的政策案例分析",
      suggestedNodes: ["国内案例", "国际案例", "经验借鉴", "比较分析"],
      relationshipToCore: "提供实践参考和经验借鉴",
    },
    {
      module_type: "policy_recommendations",
      title: "政策建议",
      icon: "💡",
      color: "#EC4899",
      description: "基于研究的政策建议和优化方向",
      suggestedNodes: ["政策建议", "优化方向", "风险防范", "配套建议"],
      relationshipToCore: "提出建设性的政策建议",
    },
  ],
} satisfies BackboneModulePreset;

export const ALL_PRESETS = [
  ACADEMIC_RESEARCH,
  EXPERIMENTAL_SCIENCE,
  ENGINEERING_RESEARCH,
  POLICY_RESEARCH,
] as const satisfies readonly BackboneModulePreset[];

export type PresetId = (typeof ALL_PRESETS)[number]["id"];

export const PRESET_MAP: Record<string, BackboneModulePreset> = {
  [ACADEMIC_RESEARCH.id]: ACADEMIC_RESEARCH,
  [EXPERIMENTAL_SCIENCE.id]: EXPERIMENTAL_SCIENCE,
  [ENGINEERING_RESEARCH.id]: ENGINEERING_RESEARCH,
  [POLICY_RESEARCH.id]: POLICY_RESEARCH,
};