import type {
  BackboneModulePreset,
} from "@shared/types/graph";

export const ACADEMIC_RESEARCH = {
  id: "academic_research" as const,
  name: "backboneModules.presets.academicResearch.name",
  description: "backboneModules.presets.academicResearch.description",
  moduleTypes: [
    "research_background",
    "literature_review",
    "research_methods",
    "core_concepts",
    "application_domains",
    "future_directions",
  ],
  modules: [
    {
      module_type: "research_background",
      title: "backboneModules.presets.academicResearch.modules.research_background.title",
      icon: "📚",
      color: "#6366F1",
      description: "backboneModules.presets.academicResearch.modules.research_background.description",
      suggestedNodes: ["研究背景", "发展历程", "研究现状", "问题陈述"],
      relationshipToCore: "backboneModules.presets.academicResearch.modules.research_background.relationshipToCore",
    },
    {
      module_type: "literature_review",
      title: "backboneModules.presets.academicResearch.modules.literature_review.title",
      icon: "📄",
      color: "#8B5CF6",
      description: "backboneModules.presets.academicResearch.modules.literature_review.description",
      suggestedNodes: ["理论基础", "相关工作", "研究空白", "文献分析"],
      relationshipToCore: "backboneModules.presets.academicResearch.modules.literature_review.relationshipToCore",
    },
    {
      module_type: "research_methods",
      title: "backboneModules.presets.academicResearch.modules.research_methods.title",
      icon: "🔬",
      color: "#3B82F6",
      description: "backboneModules.presets.academicResearch.modules.research_methods.description",
      suggestedNodes: ["研究方法", "技术路线", "实验设计", "数据分析"],
      relationshipToCore: "backboneModules.presets.academicResearch.modules.research_methods.relationshipToCore",
    },
    {
      module_type: "core_concepts",
      title: "backboneModules.presets.academicResearch.modules.core_concepts.title",
      icon: "💡",
      color: "#10B981",
      description: "backboneModules.presets.academicResearch.modules.core_concepts.description",
      suggestedNodes: ["核心概念", "关键定义", "理论框架", "主要发现"],
      relationshipToCore: "backboneModules.presets.academicResearch.modules.core_concepts.relationshipToCore",
    },
    {
      module_type: "application_domains",
      title: "backboneModules.presets.academicResearch.modules.application_domains.title",
      icon: "🎯",
      color: "#F59E0B",
      description: "backboneModules.presets.academicResearch.modules.application_domains.description",
      suggestedNodes: ["应用场景", "实践案例", "行业应用", "工具实现"],
      relationshipToCore: "backboneModules.presets.academicResearch.modules.application_domains.relationshipToCore",
    },
    {
      module_type: "future_directions",
      title: "backboneModules.presets.academicResearch.modules.future_directions.title",
      icon: "🚀",
      color: "#EC4899",
      description: "backboneModules.presets.academicResearch.modules.future_directions.description",
      suggestedNodes: ["研究展望", "发展趋势", "开放问题", "潜在方向"],
      relationshipToCore: "backboneModules.presets.academicResearch.modules.future_directions.relationshipToCore",
    },
  ],
} satisfies BackboneModulePreset;

export const EXPERIMENTAL_SCIENCE = {
  id: "experimental_science" as const,
  name: "backboneModules.presets.experimentalScience.name",
  description: "backboneModules.presets.experimentalScience.description",
  moduleTypes: [
    "research_background",
    "literature_review",
    "experiment_design",
    "data_collection",
    "result_analysis",
    "application_domains",
  ],
  modules: [
    {
      module_type: "research_background",
      title: "backboneModules.presets.experimentalScience.modules.research_background.title",
      icon: "📚",
      color: "#6366F1",
      description: "backboneModules.presets.experimentalScience.modules.research_background.description",
      suggestedNodes: ["研究背景", "问题陈述", "研究意义"],
      relationshipToCore: "backboneModules.presets.experimentalScience.modules.research_background.relationshipToCore",
    },
    {
      module_type: "literature_review",
      title: "backboneModules.presets.experimentalScience.modules.literature_review.title",
      icon: "📄",
      color: "#8B5CF6",
      description: "backboneModules.presets.experimentalScience.modules.literature_review.description",
      suggestedNodes: ["理论基础", "相关工作", "研究空白"],
      relationshipToCore: "backboneModules.presets.experimentalScience.modules.literature_review.relationshipToCore",
    },
    {
      module_type: "experiment_design",
      title: "backboneModules.presets.experimentalScience.modules.experiment_design.title",
      icon: "🧪",
      color: "#3B82F6",
      description: "backboneModules.presets.experimentalScience.modules.experiment_design.description",
      suggestedNodes: ["实验方案", "对照组设计", "变量控制", "实验工具"],
      relationshipToCore: "backboneModules.presets.experimentalScience.modules.experiment_design.relationshipToCore",
    },
    {
      module_type: "data_collection",
      title: "backboneModules.presets.experimentalScience.modules.data_collection.title",
      icon: "📊",
      color: "#10B981",
      description: "backboneModules.presets.experimentalScience.modules.data_collection.description",
      suggestedNodes: ["数据来源", "采集方法", "数据处理", "质量控制"],
      relationshipToCore: "backboneModules.presets.experimentalScience.modules.data_collection.relationshipToCore",
    },
    {
      module_type: "result_analysis",
      title: "backboneModules.presets.experimentalScience.modules.result_analysis.title",
      icon: "📈",
      color: "#F59E0B",
      description: "backboneModules.presets.experimentalScience.modules.result_analysis.description",
      suggestedNodes: ["统计分析", "结果解读", "假设验证", "误差分析"],
      relationshipToCore: "backboneModules.presets.experimentalScience.modules.result_analysis.relationshipToCore",
    },
    {
      module_type: "application_domains",
      title: "backboneModules.presets.experimentalScience.modules.application_domains.title",
      icon: "🎯",
      color: "#EC4899",
      description: "backboneModules.presets.experimentalScience.modules.application_domains.description",
      suggestedNodes: ["应用场景", "实践意义", "未来方向"],
      relationshipToCore: "backboneModules.presets.experimentalScience.modules.application_domains.relationshipToCore",
    },
  ],
} satisfies BackboneModulePreset;

export const ENGINEERING_RESEARCH = {
  id: "engineering_research" as const,
  name: "backboneModules.presets.engineeringResearch.name",
  description: "backboneModules.presets.engineeringResearch.description",
  moduleTypes: [
    "problem_background",
    "tech_architecture",
    "engineering_implementation",
    "performance_evaluation",
    "application_cases",
    "future_directions",
  ],
  modules: [
    {
      module_type: "problem_background",
      title: "backboneModules.presets.engineeringResearch.modules.problem_background.title",
      icon: "📚",
      color: "#6366F1",
      description: "backboneModules.presets.engineeringResearch.modules.problem_background.description",
      suggestedNodes: ["问题定义", "需求分析", "现有方案", "技术挑战"],
      relationshipToCore: "backboneModules.presets.engineeringResearch.modules.problem_background.relationshipToCore",
    },
    {
      module_type: "tech_architecture",
      title: "backboneModules.presets.engineeringResearch.modules.tech_architecture.title",
      icon: "🏗️",
      color: "#8B5CF6",
      description: "backboneModules.presets.engineeringResearch.modules.tech_architecture.description",
      suggestedNodes: ["架构设计", "技术选型", "模块划分", "接口定义"],
      relationshipToCore: "backboneModules.presets.engineeringResearch.modules.tech_architecture.relationshipToCore",
    },
    {
      module_type: "engineering_implementation",
      title: "backboneModules.presets.engineeringResearch.modules.engineering_implementation.title",
      icon: "⚙️",
      color: "#3B82F6",
      description: "backboneModules.presets.engineeringResearch.modules.engineering_implementation.description",
      suggestedNodes: ["核心实现", "关键技术", "实现难点", "优化方案"],
      relationshipToCore: "backboneModules.presets.engineeringResearch.modules.engineering_implementation.relationshipToCore",
    },
    {
      module_type: "performance_evaluation",
      title: "backboneModules.presets.engineeringResearch.modules.performance_evaluation.title",
      icon: "📊",
      color: "#10B981",
      description: "backboneModules.presets.engineeringResearch.modules.performance_evaluation.description",
      suggestedNodes: ["性能指标", "测试方法", "评估结果", "对比分析"],
      relationshipToCore: "backboneModules.presets.engineeringResearch.modules.performance_evaluation.relationshipToCore",
    },
    {
      module_type: "application_cases",
      title: "backboneModules.presets.engineeringResearch.modules.application_cases.title",
      icon: "🎯",
      color: "#F59E0B",
      description: "backboneModules.presets.engineeringResearch.modules.application_cases.description",
      suggestedNodes: ["应用场景", "案例分析", "用户反馈", "部署方案"],
      relationshipToCore: "backboneModules.presets.engineeringResearch.modules.application_cases.relationshipToCore",
    },
    {
      module_type: "future_directions",
      title: "backboneModules.presets.engineeringResearch.modules.future_directions.title",
      icon: "🚀",
      color: "#EC4899",
      description: "backboneModules.presets.engineeringResearch.modules.future_directions.description",
      suggestedNodes: ["技术演进", "功能扩展", "性能优化", "生态建设"],
      relationshipToCore: "backboneModules.presets.engineeringResearch.modules.future_directions.relationshipToCore",
    },
  ],
} satisfies BackboneModulePreset;

export const POLICY_RESEARCH = {
  id: "policy_research" as const,
  name: "backboneModules.presets.policyResearch.name",
  description: "backboneModules.presets.policyResearch.description",
  moduleTypes: [
    "policy_background",
    "policy_instruments",
    "implementation_mechanism",
    "impact_evaluation",
    "case_studies",
    "policy_recommendations",
  ],
  modules: [
    {
      module_type: "policy_background",
      title: "backboneModules.presets.policyResearch.modules.policy_background.title",
      icon: "📚",
      color: "#6366F1",
      description: "backboneModules.presets.policyResearch.modules.policy_background.description",
      suggestedNodes: ["政策背景", "历史沿革", "政策环境", "问题界定"],
      relationshipToCore: "backboneModules.presets.policyResearch.modules.policy_background.relationshipToCore",
    },
    {
      module_type: "policy_instruments",
      title: "backboneModules.presets.policyResearch.modules.policy_instruments.title",
      icon: "🔧",
      color: "#8B5CF6",
      description: "backboneModules.presets.policyResearch.modules.policy_instruments.description",
      suggestedNodes: ["政策工具", "配套措施", "资源配置", "制度设计"],
      relationshipToCore: "backboneModules.presets.policyResearch.modules.policy_instruments.relationshipToCore",
    },
    {
      module_type: "implementation_mechanism",
      title: "backboneModules.presets.policyResearch.modules.implementation_mechanism.title",
      icon: "⚙️",
      color: "#3B82F6",
      description: "backboneModules.presets.policyResearch.modules.implementation_mechanism.description",
      suggestedNodes: ["执行机制", "责任分工", "监督机制", "协调机制"],
      relationshipToCore: "backboneModules.presets.policyResearch.modules.implementation_mechanism.relationshipToCore",
    },
    {
      module_type: "impact_evaluation",
      title: "backboneModules.presets.policyResearch.modules.impact_evaluation.title",
      icon: "📊",
      color: "#10B981",
      description: "backboneModules.presets.policyResearch.modules.impact_evaluation.description",
      suggestedNodes: ["效果评估", "社会影响", "经济影响", "环境影响"],
      relationshipToCore: "backboneModules.presets.policyResearch.modules.impact_evaluation.relationshipToCore",
    },
    {
      module_type: "case_studies",
      title: "backboneModules.presets.policyResearch.modules.case_studies.title",
      icon: "📋",
      color: "#F59E0B",
      description: "backboneModules.presets.policyResearch.modules.case_studies.description",
      suggestedNodes: ["国内案例", "国际案例", "经验借鉴", "比较分析"],
      relationshipToCore: "backboneModules.presets.policyResearch.modules.case_studies.relationshipToCore",
    },
    {
      module_type: "policy_recommendations",
      title: "backboneModules.presets.policyResearch.modules.policy_recommendations.title",
      icon: "💡",
      color: "#EC4899",
      description: "backboneModules.presets.policyResearch.modules.policy_recommendations.description",
      suggestedNodes: ["政策建议", "优化方向", "风险防范", "配套建议"],
      relationshipToCore: "backboneModules.presets.policyResearch.modules.policy_recommendations.relationshipToCore",
    },
  ],
} satisfies BackboneModulePreset;

export const ALL_PRESETS = [
  ACADEMIC_RESEARCH,
  EXPERIMENTAL_SCIENCE,
  ENGINEERING_RESEARCH,
  POLICY_RESEARCH,
] as const satisfies readonly BackboneModulePreset[];

export type PresetId = (typeof ALL_PRESETS)[number]["id"];

export const PRESET_MAP: Record<string, BackboneModulePreset> = {
  [ACADEMIC_RESEARCH.id]: ACADEMIC_RESEARCH,
  [EXPERIMENTAL_SCIENCE.id]: EXPERIMENTAL_SCIENCE,
  [ENGINEERING_RESEARCH.id]: ENGINEERING_RESEARCH,
  [POLICY_RESEARCH.id]: POLICY_RESEARCH,
};
