export const ErrorCodes = {
  AUTH_HEADER_MISSING: "AUTH_HEADER_MISSING",
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_REVOKED: "AUTH_TOKEN_REVOKED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_NOT_CONFIRMED: "EMAIL_NOT_CONFIRMED",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  WEAK_PASSWORD: "WEAK_PASSWORD",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INVALID_EMAIL: "INVALID_EMAIL",
  SIGNUP_DISABLED: "SIGNUP_DISABLED",
  LOGIN_FAILED: "LOGIN_FAILED",
  REGISTER_FAILED: "REGISTER_FAILED",
  SESSION_REFRESH_FAILED: "SESSION_REFRESH_FAILED",
  TOKEN_REFRESH_EXPIRED: "TOKEN_REFRESH_EXPIRED",
  MISSING_REFRESH_TOKEN: "MISSING_REFRESH_TOKEN",
  LOGOUT_FAILED: "LOGOUT_FAILED",
  PASSWORD_REQUIREMENTS: "PASSWORD_REQUIREMENTS",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_GRAPH_NOT_FOUND: "RESOURCE_GRAPH_NOT_FOUND",
  RESOURCE_NODE_NOT_FOUND: "RESOURCE_NODE_NOT_FOUND",
  RESOURCE_CARD_NOT_FOUND: "RESOURCE_CARD_NOT_FOUND",
  RESOURCE_TASK_NOT_FOUND: "RESOURCE_TASK_NOT_FOUND",
  RESOURCE_PATH_NOT_FOUND: "RESOURCE_PATH_NOT_FOUND",
  RESOURCE_TEMPLATE_NOT_FOUND: "RESOURCE_TEMPLATE_NOT_FOUND",
  RESOURCE_USER_NOT_FOUND: "RESOURCE_USER_NOT_FOUND",

  VALIDATION_ERROR: "VALIDATION_ERROR",
  VALIDATION_INVALID_JSON: "VALIDATION_INVALID_JSON",
  VALIDATION_INVALID_PARAMS: "VALIDATION_INVALID_PARAMS",
  VALIDATION_MISSING_FIELD: "VALIDATION_MISSING_FIELD",
  VALIDATION_INVALID_FORMAT: "VALIDATION_INVALID_FORMAT",

  DATABASE_DUPLICATE_ENTRY: "DATABASE_DUPLICATE_ENTRY",
  DATABASE_FOREIGN_KEY_VIOLATION: "DATABASE_FOREIGN_KEY_VIOLATION",
  DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",
  DATABASE_QUERY_ERROR: "DATABASE_QUERY_ERROR",

  DUPLICATE_TOPIC: "DUPLICATE_TOPIC",

  AI_SERVICE_UNAVAILABLE: "AI_SERVICE_UNAVAILABLE",
  AI_RATE_LIMIT_EXCEEDED: "AI_RATE_LIMIT_EXCEEDED",
  AI_PROVIDER_ERROR: "AI_PROVIDER_ERROR",
  AI_TIMEOUT: "AI_TIMEOUT",
  AI_INVALID_RESPONSE: "AI_INVALID_RESPONSE",
  AI_EMBEDDING_ERROR: "AI_EMBEDDING_ERROR",

  LITERATURE_EXTRACT_FAILED: "LITERATURE_EXTRACT_FAILED",
  LITERATURE_APPLY_FAILED: "LITERATURE_APPLY_FAILED",
  LITERATURE_PARSE_FAILED: "LITERATURE_PARSE_FAILED",
  BACKBONE_GENERATION_FAILED: "BACKBONE_GENERATION_FAILED",
  CONCEPT_AGGREGATION_FAILED: "CONCEPT_AGGREGATION_FAILED",
  URL_FETCH_FAILED: "URL_FETCH_FAILED",
  SSRF_BLOCKED: "SSRF_BLOCKED",

  LEARNING_CARD_GENERATION_FAILED: "LEARNING_CARD_GENERATION_FAILED",
  LEARNING_FSRS_ERROR: "LEARNING_FSRS_ERROR",
  LEARNING_PROGRESS_ERROR: "LEARNING_PROGRESS_ERROR",
  LEARNING_QUIZ_ERROR: "LEARNING_QUIZ_ERROR",

  SCHEDULER_TASK_CREATION_FAILED: "SCHEDULER_TASK_CREATION_FAILED",
  SCHEDULER_TASK_EXECUTION_FAILED: "SCHEDULER_TASK_EXECUTION_FAILED",
  SCHEDULER_DEPENDENCY_ERROR: "SCHEDULER_DEPENDENCY_ERROR",
  SCHEDULER_QUEUE_ERROR: "SCHEDULER_QUEUE_ERROR",

  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_INVALID_TYPE: "FILE_INVALID_TYPE",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",

  SYSTEM_INTERNAL_ERROR: "SYSTEM_INTERNAL_ERROR",
  SYSTEM_MAINTENANCE: "SYSTEM_MAINTENANCE",
  SYSTEM_CONFIGURATION_ERROR: "SYSTEM_CONFIGURATION_ERROR",

  NETWORK_ERROR: "NETWORK_ERROR",
  CANCELLED_ERROR: "CANCELLED_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  UNSUPPORTED_FORMAT: "UNSUPPORTED_FORMAT",
  CANNOT_MODIFY_SYSTEM_TEMPLATE: "CANNOT_MODIFY_SYSTEM_TEMPLATE",
  AI_PROVIDER_NOT_CONFIGURED: "AI_PROVIDER_NOT_CONFIGURED",
  TTS_PROVIDER_NOT_CONFIGURED: "TTS_PROVIDER_NOT_CONFIGURED",
  STT_PROVIDER_NOT_CONFIGURED: "STT_PROVIDER_NOT_CONFIGURED",
  NO_FILE_UPLOADED: "NO_FILE_UPLOADED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const ErrorCodeMessageKeys: Record<ErrorCode, string> = {
  AUTH_HEADER_MISSING: "errors.errorCodes.authHeaderMissing",
  AUTH_TOKEN_MISSING: "errors.errorCodes.authTokenMissing",
  AUTH_TOKEN_INVALID: "errors.errorCodes.authTokenInvalid",
  AUTH_TOKEN_EXPIRED: "errors.errorCodes.authTokenExpired",
  AUTH_TOKEN_REVOKED: "errors.errorCodes.authTokenRevoked",
  AUTH_UNAUTHORIZED: "errors.errorCodes.authUnauthorized",
  AUTH_FORBIDDEN: "errors.errorCodes.authForbidden",

  INVALID_CREDENTIALS: "errors.errorCodes.invalidCredentials",
  EMAIL_NOT_CONFIRMED: "errors.errorCodes.emailNotConfirmed",
  TOO_MANY_REQUESTS: "errors.errorCodes.tooManyRequests",
  WEAK_PASSWORD: "errors.errorCodes.weakPassword",
  EMAIL_ALREADY_EXISTS: "errors.errorCodes.emailAlreadyExists",
  INVALID_EMAIL: "errors.errorCodes.invalidEmail",
  SIGNUP_DISABLED: "errors.errorCodes.signupDisabled",
  LOGIN_FAILED: "errors.errorCodes.loginFailed",
  REGISTER_FAILED: "errors.errorCodes.registerFailed",
  SESSION_REFRESH_FAILED: "errors.errorCodes.sessionRefreshFailed",
  TOKEN_REFRESH_EXPIRED: "errors.errorCodes.tokenRefreshExpired",
  MISSING_REFRESH_TOKEN: "errors.errorCodes.missingRefreshToken",
  LOGOUT_FAILED: "errors.errorCodes.logoutFailed",
  PASSWORD_REQUIREMENTS: "errors.errorCodes.passwordRequirements",

  RESOURCE_NOT_FOUND: "errors.errorCodes.resourceNotFound",
  RESOURCE_GRAPH_NOT_FOUND: "errors.errorCodes.resourceGraphNotFound",
  RESOURCE_NODE_NOT_FOUND: "errors.errorCodes.resourceNodeNotFound",
  RESOURCE_CARD_NOT_FOUND: "errors.errorCodes.resourceCardNotFound",
  RESOURCE_TASK_NOT_FOUND: "errors.errorCodes.resourceTaskNotFound",
  RESOURCE_PATH_NOT_FOUND: "errors.errorCodes.resourcePathNotFound",
  RESOURCE_TEMPLATE_NOT_FOUND: "errors.errorCodes.resourceTemplateNotFound",
  RESOURCE_USER_NOT_FOUND: "errors.errorCodes.resourceUserNotFound",

  VALIDATION_ERROR: "errors.errorCodes.validationError",
  VALIDATION_INVALID_JSON: "errors.errorCodes.validationInvalidJson",
  VALIDATION_INVALID_PARAMS: "errors.errorCodes.validationInvalidParams",
  VALIDATION_MISSING_FIELD: "errors.errorCodes.validationMissingField",
  VALIDATION_INVALID_FORMAT: "errors.errorCodes.validationInvalidFormat",

  DATABASE_DUPLICATE_ENTRY: "errors.errorCodes.databaseDuplicateEntry",
  DATABASE_FOREIGN_KEY_VIOLATION:
    "errors.errorCodes.databaseForeignKeyViolation",
  DATABASE_CONNECTION_ERROR: "errors.errorCodes.databaseConnectionError",
  DATABASE_QUERY_ERROR: "errors.errorCodes.databaseQueryError",

  DUPLICATE_TOPIC: "errors.errorCodes.duplicateTopic",

  AI_SERVICE_UNAVAILABLE: "errors.errorCodes.aiServiceUnavailable",
  AI_RATE_LIMIT_EXCEEDED: "errors.errorCodes.aiRateLimitExceeded",
  AI_PROVIDER_ERROR: "errors.errorCodes.aiProviderError",
  AI_TIMEOUT: "errors.errorCodes.aiTimeout",
  AI_INVALID_RESPONSE: "errors.errorCodes.aiInvalidResponse",
  AI_EMBEDDING_ERROR: "errors.errorCodes.aiEmbeddingError",

  LITERATURE_EXTRACT_FAILED: "errors.errorCodes.literatureExtractFailed",
  LITERATURE_APPLY_FAILED: "errors.errorCodes.literatureApplyFailed",
  LITERATURE_PARSE_FAILED: "errors.errorCodes.literatureParseFailed",
  BACKBONE_GENERATION_FAILED: "errors.errorCodes.backboneGenerationFailed",
  CONCEPT_AGGREGATION_FAILED: "errors.errorCodes.conceptAggregationFailed",
  URL_FETCH_FAILED: "errors.errorCodes.urlFetchFailed",
  SSRF_BLOCKED: "errors.errorCodes.ssrfBlocked",

  LEARNING_CARD_GENERATION_FAILED:
    "errors.errorCodes.learningCardGenerationFailed",
  LEARNING_FSRS_ERROR: "errors.errorCodes.learningFsrsError",
  LEARNING_PROGRESS_ERROR: "errors.errorCodes.learningProgressError",
  LEARNING_QUIZ_ERROR: "errors.errorCodes.learningQuizError",

  SCHEDULER_TASK_CREATION_FAILED:
    "errors.errorCodes.schedulerTaskCreationFailed",
  SCHEDULER_TASK_EXECUTION_FAILED:
    "errors.errorCodes.schedulerTaskExecutionFailed",
  SCHEDULER_DEPENDENCY_ERROR: "errors.errorCodes.schedulerDependencyError",
  SCHEDULER_QUEUE_ERROR: "errors.errorCodes.schedulerQueueError",

  FILE_TOO_LARGE: "errors.errorCodes.fileTooLarge",
  FILE_INVALID_TYPE: "errors.errorCodes.fileInvalidType",
  FILE_UPLOAD_FAILED: "errors.errorCodes.fileUploadFailed",

  SYSTEM_INTERNAL_ERROR: "errors.errorCodes.systemInternalError",
  SYSTEM_MAINTENANCE: "errors.errorCodes.systemMaintenance",
  SYSTEM_CONFIGURATION_ERROR: "errors.errorCodes.systemConfigurationError",

  NETWORK_ERROR: "errors.errorCodes.networkError",
  CANCELLED_ERROR: "errors.errorCodes.cancelledError",
  UNKNOWN_ERROR: "errors.errorCodes.unknownError",
  UNSUPPORTED_FORMAT: "errors.errorCodes.unsupportedFormat",
  CANNOT_MODIFY_SYSTEM_TEMPLATE: "errors.errorCodes.cannotModifySystemTemplate",
  AI_PROVIDER_NOT_CONFIGURED: "errors.errorCodes.aiProviderNotConfigured",
  TTS_PROVIDER_NOT_CONFIGURED: "errors.errorCodes.ttsProviderNotConfigured",
  STT_PROVIDER_NOT_CONFIGURED: "errors.errorCodes.sttProviderNotConfigured",
  NO_FILE_UPLOADED: "errors.errorCodes.noFileUploaded",
};

export const ErrorCodeStatus: Record<ErrorCode, number> = {
  AUTH_HEADER_MISSING: 401,
  AUTH_TOKEN_MISSING: 401,
  AUTH_TOKEN_INVALID: 401,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_TOKEN_REVOKED: 401,
  AUTH_UNAUTHORIZED: 401,
  AUTH_FORBIDDEN: 403,

  INVALID_CREDENTIALS: 401,
  EMAIL_NOT_CONFIRMED: 401,
  TOO_MANY_REQUESTS: 429,
  WEAK_PASSWORD: 400,
  EMAIL_ALREADY_EXISTS: 409,
  INVALID_EMAIL: 400,
  SIGNUP_DISABLED: 403,
  LOGIN_FAILED: 401,
  REGISTER_FAILED: 400,
  SESSION_REFRESH_FAILED: 401,
  TOKEN_REFRESH_EXPIRED: 401,
  MISSING_REFRESH_TOKEN: 400,
  LOGOUT_FAILED: 500,
  PASSWORD_REQUIREMENTS: 400,

  RESOURCE_NOT_FOUND: 404,
  RESOURCE_GRAPH_NOT_FOUND: 404,
  RESOURCE_NODE_NOT_FOUND: 404,
  RESOURCE_CARD_NOT_FOUND: 404,
  RESOURCE_TASK_NOT_FOUND: 404,
  RESOURCE_PATH_NOT_FOUND: 404,
  RESOURCE_TEMPLATE_NOT_FOUND: 404,
  RESOURCE_USER_NOT_FOUND: 404,

  VALIDATION_ERROR: 400,
  VALIDATION_INVALID_JSON: 400,
  VALIDATION_INVALID_PARAMS: 400,
  VALIDATION_MISSING_FIELD: 400,
  VALIDATION_INVALID_FORMAT: 400,

  DATABASE_DUPLICATE_ENTRY: 409,
  DATABASE_FOREIGN_KEY_VIOLATION: 400,
  DATABASE_CONNECTION_ERROR: 503,
  DATABASE_QUERY_ERROR: 500,

  DUPLICATE_TOPIC: 409,

  AI_SERVICE_UNAVAILABLE: 503,
  AI_RATE_LIMIT_EXCEEDED: 429,
  AI_PROVIDER_ERROR: 502,
  AI_TIMEOUT: 504,
  AI_INVALID_RESPONSE: 502,
  AI_EMBEDDING_ERROR: 500,

  LITERATURE_EXTRACT_FAILED: 500,
  LITERATURE_APPLY_FAILED: 500,
  LITERATURE_PARSE_FAILED: 400,
  BACKBONE_GENERATION_FAILED: 500,
  CONCEPT_AGGREGATION_FAILED: 500,
  URL_FETCH_FAILED: 502,
  SSRF_BLOCKED: 403,

  LEARNING_CARD_GENERATION_FAILED: 500,
  LEARNING_FSRS_ERROR: 500,
  LEARNING_PROGRESS_ERROR: 500,
  LEARNING_QUIZ_ERROR: 500,

  SCHEDULER_TASK_CREATION_FAILED: 500,
  SCHEDULER_TASK_EXECUTION_FAILED: 500,
  SCHEDULER_DEPENDENCY_ERROR: 400,
  SCHEDULER_QUEUE_ERROR: 500,

  FILE_TOO_LARGE: 413,
  FILE_INVALID_TYPE: 415,
  FILE_UPLOAD_FAILED: 500,

  SYSTEM_INTERNAL_ERROR: 500,
  SYSTEM_MAINTENANCE: 503,
  SYSTEM_CONFIGURATION_ERROR: 500,

  NETWORK_ERROR: 0,
  CANCELLED_ERROR: 0,
  UNKNOWN_ERROR: 500,
  UNSUPPORTED_FORMAT: 400,
  CANNOT_MODIFY_SYSTEM_TEMPLATE: 403,
  AI_PROVIDER_NOT_CONFIGURED: 500,
  TTS_PROVIDER_NOT_CONFIGURED: 503,
  STT_PROVIDER_NOT_CONFIGURED: 503,
  NO_FILE_UPLOADED: 400,
};

export function getErrorMessage(code: ErrorCode): string {
  return ErrorCodeMessageKeys[code];
}

export function getErrorStatus(code: ErrorCode): number {
  return ErrorCodeStatus[code];
}
