-- =====================================================
-- Knowledge Map - Learning Paths
-- =====================================================

-- Learning paths table
CREATE TABLE IF NOT EXISTS learning_paths (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  goal TEXT,
  target_date DATE,
  source_graph_id UUID REFERENCES knowledge_graphs(id) ON DELETE SET NULL,
  domain_id UUID REFERENCES domains(id) ON DELETE SET NULL,
  path_type VARCHAR(20) DEFAULT 'single_graph' CHECK (path_type IN ('single_graph', 'cross_graph')),
  total_estimated_time INTEGER DEFAULT 0,
  ai_generated BOOLEAN DEFAULT FALSE,
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'completed', 'paused', 'archived')),
  daily_minutes_target INTEGER DEFAULT 30,
  scheduled_start_date DATE,
  scheduled_end_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE learning_paths IS 'Learning paths for structured learning journeys';
COMMENT ON COLUMN learning_paths.goal IS 'Learning goal description';
COMMENT ON COLUMN learning_paths.target_date IS 'Target completion date';
COMMENT ON COLUMN learning_paths.source_graph_id IS 'Source graph for this learning path';
COMMENT ON COLUMN learning_paths.total_estimated_time IS 'Total estimated time in minutes';
COMMENT ON COLUMN learning_paths.ai_generated IS 'Whether this path was generated by AI';
COMMENT ON COLUMN learning_paths.daily_minutes_target IS 'Daily learning time target in minutes';
COMMENT ON COLUMN learning_paths.scheduled_start_date IS '学习窗口（路径）计划开始日，排课首日';
COMMENT ON COLUMN learning_paths.scheduled_end_date IS '学习窗口（路径）计划结束日，可由预估总时长/每日目标推导';

-- Learning path nodes table
CREATE TABLE IF NOT EXISTS learning_path_nodes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  path_id UUID NOT NULL REFERENCES learning_paths(id) ON DELETE CASCADE,
  knowledge_point_id UUID REFERENCES knowledge_points(id) ON DELETE SET NULL,
  graph_id UUID REFERENCES knowledge_graphs(id) ON DELETE SET NULL,
  order_index INTEGER NOT NULL DEFAULT 0,
  title TEXT NOT NULL,
  description TEXT,
  estimated_time INTEGER DEFAULT 30,
  is_milestone BOOLEAN DEFAULT FALSE,
  prerequisites UUID[] DEFAULT '{}',
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'skipped')),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE learning_path_nodes IS 'Nodes in a learning path';
COMMENT ON COLUMN learning_path_nodes.order_index IS 'Order of this node in the path';
COMMENT ON COLUMN learning_path_nodes.estimated_time IS 'Estimated time in minutes';
COMMENT ON COLUMN learning_path_nodes.is_milestone IS 'Whether this node is a milestone';
COMMENT ON COLUMN learning_path_nodes.prerequisites IS '[DEPRECATED] 使用 learning_path_prerequisites 关联表替代此 UUID[] 列';

-- Learning path prerequisites table
CREATE TABLE IF NOT EXISTS learning_path_prerequisites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  path_node_id UUID NOT NULL REFERENCES learning_path_nodes(id) ON DELETE CASCADE,
  prerequisite_node_id UUID NOT NULL REFERENCES learning_path_nodes(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(path_node_id, prerequisite_node_id),
  CHECK(path_node_id != prerequisite_node_id)
);

COMMENT ON TABLE learning_path_prerequisites IS '学习路径节点前置依赖关联表，替代 learning_path_nodes.prerequisites UUID[] 列';
COMMENT ON COLUMN learning_path_prerequisites.path_node_id IS '依赖方节点ID';
COMMENT ON COLUMN learning_path_prerequisites.prerequisite_node_id IS '被依赖的前置节点ID';

-- Learning path progress table
CREATE TABLE IF NOT EXISTS learning_path_progress (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  path_id UUID NOT NULL REFERENCES learning_paths(id) ON DELETE CASCADE,
  node_id UUID NOT NULL REFERENCES learning_path_nodes(id) ON DELETE CASCADE,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'skipped')),
  progress_percentage INTEGER DEFAULT 0 CHECK (progress_percentage BETWEEN 0 AND 100),
  time_spent INTEGER DEFAULT 0,
  notes TEXT,
  planned_duration INTEGER DEFAULT 0,
  planned_nodes UUID[] DEFAULT '{}',
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, path_id, node_id)
);

COMMENT ON TABLE learning_path_progress IS 'User progress on learning path nodes (merged with learning_plans)';
COMMENT ON COLUMN learning_path_progress.time_spent IS 'Time spent in minutes';
COMMENT ON COLUMN learning_path_progress.progress_percentage IS 'Progress percentage (0-100)';
COMMENT ON COLUMN learning_path_progress.planned_duration IS 'Planned duration in minutes (migrated from learning_plans)';
COMMENT ON COLUMN learning_path_progress.planned_nodes IS 'Array of learning_path_node IDs planned (migrated from learning_plans)';

-- Path node tasks table
CREATE TABLE IF NOT EXISTS path_node_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  path_id UUID NOT NULL REFERENCES learning_paths(id) ON DELETE CASCADE,
  node_id UUID NOT NULL REFERENCES learning_path_nodes(id) ON DELETE CASCADE,
  task_id UUID NOT NULL REFERENCES user_tasks(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(node_id, task_id)
);

COMMENT ON TABLE path_node_tasks IS '学习路径节点与任务的关联表';
COMMENT ON COLUMN path_node_tasks.path_id IS '学习路径 ID';
COMMENT ON COLUMN path_node_tasks.node_id IS '学习路径节点 ID';
COMMENT ON COLUMN path_node_tasks.task_id IS '关联的任务 ID';

-- Learning loops table
CREATE TABLE IF NOT EXISTS learning_loops (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  knowledge_point_id UUID REFERENCES knowledge_points(id) ON DELETE SET NULL,
  graph_id UUID REFERENCES knowledge_graphs(id) ON DELETE SET NULL,
  current_stage VARCHAR(20) DEFAULT 'learn' CHECK (current_stage IN ('learn', 'test', 'review', 'iterate')),
  mastery_level DOUBLE PRECISION DEFAULT 0,
  loop_count INTEGER DEFAULT 0,
  last_stage_change_at TIMESTAMPTZ DEFAULT NOW(),
  config JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE learning_loops IS 'Learning loop orchestrator tracking learn-test-review-iterate cycles';
COMMENT ON COLUMN learning_loops.current_stage IS 'Current stage in the learning loop';
COMMENT ON COLUMN learning_loops.mastery_level IS 'Current mastery level (0-1)';
COMMENT ON COLUMN learning_loops.loop_count IS 'Number of completed loop iterations';
COMMENT ON COLUMN learning_loops.config IS 'Loop configuration (masteryThreshold, testDelayMinutes, maxLoops)';

ALTER TABLE learning_loops ADD COLUMN IF NOT EXISTS study_mode TEXT;
ALTER TABLE learning_loops ADD COLUMN IF NOT EXISTS current_workflow_stage TEXT;

-- Add foreign key constraint for task_subtasks.learning_path_node_id
ALTER TABLE task_subtasks
  ADD CONSTRAINT fk_task_subtasks_learning_path_node
  FOREIGN KEY (learning_path_node_id) REFERENCES learning_path_nodes(id) ON DELETE SET NULL;

-- Learning path schedule table（日历自动排课 Phase A）
-- 以 knowledge_point_id 为排期主体，scheduled_date 为排期日期，
-- 全局唯一键 (user_id, knowledge_point_id, scheduled_date) 强制同一知识点同日只有一条排期，
-- 天然消解多路径复用冲突（其余来源自动合并/跳过）。
CREATE TABLE IF NOT EXISTS learning_path_schedule (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  knowledge_point_id UUID NOT NULL REFERENCES knowledge_points(id) ON DELETE CASCADE,
  scheduled_date DATE NOT NULL,
  path_id UUID REFERENCES learning_paths(id) ON DELETE CASCADE,
  source_path_ids UUID[] DEFAULT '{}',
  estimated_time INTEGER DEFAULT 30,
  status VARCHAR(20) DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'skipped')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, knowledge_point_id, scheduled_date)
);

COMMENT ON TABLE learning_path_schedule IS '学习路径知识点排期（按知识点聚合，全局去重）';
COMMENT ON COLUMN learning_path_schedule.knowledge_point_id IS '排期主体知识点';
COMMENT ON COLUMN learning_path_schedule.scheduled_date IS '排期日期（只排日，不排时钟）';
COMMENT ON COLUMN learning_path_schedule.path_id IS '归属学习路径（即学习窗口），可为空（共享知识点多来源）';
COMMENT ON COLUMN learning_path_schedule.source_path_ids IS '来源路径数组，记录该排期由哪些学习路径发起';
COMMENT ON COLUMN learning_path_schedule.estimated_time IS '预估学习时长（分钟）';
COMMENT ON COLUMN learning_path_schedule.status IS '排期状态：scheduled(待学)/completed(已完成)/skipped(已跳过)';

ALTER TABLE learning_path_schedule ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own schedule" ON learning_path_schedule FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own schedule" ON learning_path_schedule FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own schedule" ON learning_path_schedule FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own schedule" ON learning_path_schedule FOR DELETE USING (auth.uid() = user_id);

GRANT ALL PRIVILEGES ON learning_path_schedule TO authenticated;
GRANT SELECT ON learning_path_schedule TO authenticated;
