-- =====================================================
-- Knowledge Map - pgvector 向量相似度搜索
-- =====================================================

-- 向量索引已在 12_indexes.sql 中使用 HNSW 创建（更优的索引类型）
-- HNSW 索引相比 IVFFlat 的优势：
-- 1. 不需要预训练数据量（IVFFlat 需要至少约 1000 个向量）
-- 2. 查询性能更稳定，召回率更高
-- 3. 增量更新不需要重建索引
-- 
-- 已有的 HNSW 索引：
--   idx_knowledge_points_embedding ON knowledge_points USING hnsw (embedding vector_cosine_ops)
--   knowledge_graphs_embedding_idx ON knowledge_graphs USING hnsw (embedding vector_cosine_ops)
